# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 709ab718c60484f1604d703b54ad3221d887deabf19e35712bcda93575def0681a33270fba1036cb72eb3c12c2c8ac49274459f7666ccff93d38fdd7a26e8930

test:
  secret_key_base: f670f3bddf3028a13a9eadb4939fffb29ce62d14c50a88193bca75c8b5d8d1a5e42ddd77cb3706d3bdc947cf4ee3c55dd551932c5fa0c52239adb60005c92ff4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
